In [1]:
li='Fahad'

In [2]:
li.isalpha()

True

In [3]:
li.isnumeric()

False

In [4]:
li.islower()

False

In [6]:
li.isupper()

False

In [11]:
li.index('a')

1

In [12]:
li.istitle()

True

In [13]:
name='fahad'
dept='bda'

In [14]:
name.isalpha() or dept.isnumeric()

True

In [20]:
lis=[1,2,3,'fahad','adarsh']
lis.append('faad')

In [21]:
lis

[1, 2, 3, 'fahad', 'adarsh', 'faad']

In [22]:
lis.append(1)

In [23]:
lis

[1, 2, 3, 'fahad', 'adarsh', 'faad', 1]

In [24]:
lis.append(['fahad,mangesh'])

In [25]:
lis

[1, 2, 3, 'fahad', 'adarsh', 'faad', 1, ['fahad,mangesh']]

In [26]:
lis.insert(2,'faris')

In [27]:
lis

[1, 2, 'faris', 3, 'fahad', 'adarsh', 'faad', 1, ['fahad,mangesh']]

In [29]:
lis.extend([23,24,25])

In [30]:
lis

[1, 2, 'faris', 3, 'fahad', 'adarsh', 'faad', 1, ['fahad,mangesh'], 23, 24, 25]

In [31]:
li=[1,2,3,4,5]
sum(li)

15

In [32]:
li.pop(2)

3

In [33]:
li

[1, 2, 4, 5]

In [34]:
#sets

In [35]:
s={'fahad','faris','mangesh'}
type(s)

set

In [36]:
s.add(1)

In [37]:
s

{1, 'fahad', 'faris', 'mangesh'}

In [38]:
s.add(1)

In [39]:
s

{1, 'fahad', 'faris', 'mangesh'}

In [41]:
se={'fahad','faris','mangesh'}
s.difference(se)

{1}

In [42]:
se.difference(s)

set()

In [43]:
se.intersection(s)

{'fahad', 'faris', 'mangesh'}

In [44]:
se.issubset(s)

True

In [46]:
s.difference_update(se)

In [47]:
s

{1}

In [48]:
se

{'fahad', 'faris', 'mangesh'}

In [49]:
s.intersection(se)

set()

In [50]:
#dictionary

In [51]:
d={}
type(d)

dict

In [52]:
type(dict())

dict

In [53]:
dic={1:'fahad',2:'faris'}
dic

{1: 'fahad', 2: 'faris'}

In [54]:
dic[1]

'fahad'

In [57]:
dic.keys()

dict_keys([1, 2])

In [58]:
dic.values()

dict_values(['fahad', 'faris'])

In [59]:
for i in dic.keys():
    print(i)

1
2


In [60]:
dic.items()

dict_items([(1, 'fahad'), (2, 'faris')])

In [61]:
dic[3]='mangesh'
dic

{1: 'fahad', 2: 'faris', 3: 'mangesh'}

In [62]:
dic[1]='faaaad'
dic

{1: 'faaaad', 2: 'faris', 3: 'mangesh'}

In [63]:
#nested dictionary

In [64]:
dic={1:{'fahad':24},2:{'faris':20}}
dic

{1: {'fahad': 24}, 2: {'faris': 20}}

In [65]:
dic[1]

{'fahad': 24}

In [68]:
dic[1]['fahad']

24

In [69]:
dic[2]['faris']

20

In [70]:
#tuple

In [71]:
tupl=('fahad','faris')
type(tupl)

tuple

In [79]:
tupl.add('faaad')

AttributeError: 'tuple' object has no attribute 'add'

In [78]:
tupl.count('fahad')

1

In [1]:
#numpy

In [2]:
import numpy as np

In [3]:
lst=[1,2,3,4,5,6,7,8]
arr=np.array([lst])
arr

array([[1, 2, 3, 4, 5, 6, 7, 8]])

In [7]:
type(arr)

numpy.ndarray

In [8]:
arr.shape

(1, 8)

In [9]:
arr.reshape(2,4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [10]:
arr.reshape(4,2)

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [11]:
arr1=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])

In [12]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [14]:
arr1[1:,:]

array([[ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [15]:
arr1.shape

(3, 5)

In [17]:
arr1[0:2,3:]

array([[ 4,  5],
       [ 9, 10]])

In [19]:
arr=np.arange(0,10)

In [20]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
arr[5:]=100

In [22]:
arr

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100])

In [24]:
ar=np.linspace(1,5,20)
ar

array([1.        , 1.21052632, 1.42105263, 1.63157895, 1.84210526,
       2.05263158, 2.26315789, 2.47368421, 2.68421053, 2.89473684,
       3.10526316, 3.31578947, 3.52631579, 3.73684211, 3.94736842,
       4.15789474, 4.36842105, 4.57894737, 4.78947368, 5.        ])

In [25]:
arr

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100])

In [26]:
arr1=arr

In [27]:
arr1[2:4]=300

In [28]:
arr

array([  0,   1, 300, 300,   4, 100, 100, 100, 100, 100])

In [29]:
arr1

array([  0,   1, 300, 300,   4, 100, 100, 100, 100, 100])

In [31]:
#overcome these we can use copy function and broadcasting

In [32]:
ar=np.array([1,2,3,4,5,6,7])

In [33]:
ar

array([1, 2, 3, 4, 5, 6, 7])

In [34]:
ar.shape

(7,)

In [35]:
ar1=ar.copy()

In [36]:
ar1

array([1, 2, 3, 4, 5, 6, 7])

In [37]:
ar1[3:6]=100

In [38]:
ar1

array([  1,   2,   3, 100, 100, 100,   7])

In [39]:
ar

array([1, 2, 3, 4, 5, 6, 7])

In [40]:
ar<3

array([ True,  True, False, False, False, False, False])

In [41]:
ar[ar<3]

array([1, 2])

In [42]:
ar*3

array([ 3,  6,  9, 12, 15, 18, 21])

In [44]:
ar[ar<6]

array([1, 2, 3, 4, 5])

In [46]:
new=np.arange(1,11).reshape(5,2)

In [47]:
new

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [50]:
np.ones([2,3],dtype=int)

array([[1, 1, 1],
       [1, 1, 1]])

In [51]:
np.random.rand(3,3)

array([[0.37092754, 0.04796834, 0.27650836],
       [0.30278943, 0.70132191, 0.50072213],
       [0.83176544, 0.58787299, 0.7667983 ]])

In [53]:
np.random.randn(3,3)

array([[ 1.41312567, -0.00160849, -1.59700755],
       [-0.83611695, -0.35337584,  0.28578692],
       [ 1.07784213, -1.51177212,  0.81225766]])

In [54]:
np.random.randint(1,100,10)

array([ 4,  6, 80, 17, 64, 85, 68, 94,  4, 76])

In [55]:
np.random.random_sample(10)

array([0.31493998, 0.43069938, 0.6600801 , 0.0158345 , 0.58673342,
       0.27791896, 0.64225187, 0.3378282 , 0.45288983, 0.91276564])